"""
Test that capability parameters with underscore prefix are detected.

This tests the fix for false positives where functions like:
    public fun claim_fee(_admin: &AdminCap, ...) -> Coin<T>

were being flagged as missing authorization, even though the capability
parameter enforces authorization via the type system.
"""

from core.context import ProjectContext
from analysis.access_control import generate_checks_role_facts
from core.facts import Fact


def test_underscore_capability_parameter_detected():
    """Test that capability parameters with underscore prefix generate ChecksCapability facts."""

    # Create minimal context with manual facts
    ctx = ProjectContext(["test.move"])
    file_ctx = ctx.source_files["test.move"]
    file_ctx.module_path = "test::underscore_cap"

    # Manually create facts that would be generated by parser
    file_ctx.facts = [
        # Struct definition
        Fact("Struct", ("test::underscore_cap::AdminCap",)),
        Fact("IsCapability", ("test::underscore_cap::AdminCap",)),
        Fact("IsPrivileged", ("test::underscore_cap::AdminCap",)),

        # Function with underscore prefix parameter
        Fact("Fun", ("test::underscore_cap::claim_fees",)),
        Fact("FormalArg", ("test::underscore_cap::claim_fees", 0, "_admin", "&AdminCap")),
        Fact("FormalArg", ("test::underscore_cap::claim_fees", 1, "pool", "&mut Pool<T>")),

        # Function with regular parameter name
        Fact("Fun", ("test::underscore_cap::claim_fees_v2",)),
        Fact("FormalArg", ("test::underscore_cap::claim_fees_v2", 0, "admin", "&AdminCap")),
        Fact("FormalArg", ("test::underscore_cap::claim_fees_v2", 1, "pool", "&mut Pool<T>")),
    ]

    # Build global facts index
    for fact in file_ctx.facts:
        if fact.name == "Fun":
            func_name = fact.args[0]
            ctx.global_facts_index[func_name] = {"test.move": [fact]}

    # Generate ChecksCapability facts
    generate_checks_role_facts(ctx)

    # Collect all ChecksCapability facts
    checks_role_facts = [f for f in file_ctx.facts if f.name == "ChecksCapability"]

    # Check that claim_fees (with _admin parameter) has ChecksCapability fact
    claim_fees_checks_role = [
        f for f in checks_role_facts
        if f.args[1] == "test::underscore_cap::claim_fees"
    ]

    assert len(claim_fees_checks_role) > 0, \
        f"claim_fees with _admin: &AdminCap parameter should generate ChecksCapability fact. Got facts: {checks_role_facts}"

    # Verify the role type is correct
    assert claim_fees_checks_role[0].args[0] == "test::underscore_cap::AdminCap", \
        f"ChecksCapability should have AdminCap as role type, got: {claim_fees_checks_role[0].args[0]}"

    # Check that claim_fees_v2 (with admin parameter) also has ChecksCapability fact
    claim_fees_v2_checks_role = [
        f for f in checks_role_facts
        if f.args[1] == "test::underscore_cap::claim_fees_v2"
    ]

    assert len(claim_fees_v2_checks_role) > 0, \
        f"claim_fees_v2 with admin: &AdminCap parameter should generate ChecksCapability fact. Got facts: {checks_role_facts}"

    print("✓ Both functions with capability parameters (with and without underscore) generate ChecksCapability facts")


if __name__ == "__main__":
    test_underscore_capability_parameter_detected()
